<?php
    require_once '../common/set_inc.php';
    if(!isset($_SESSION['openid'])){
        //没有session,没有通过认证
        if(isset($_GET['code'])){
            //有code,已经完成跳转
            $openid=$weChat->Oauth_check($_GET['code']);
            if($openid){
                $res=$weChat->getUserInfo($openid);
                if($res['subscribe']==1){
                    //已关注
                    $_SESSION['openid']=$openid;
                    //记录用户信息
                    $username=$res['nickname'];
                    $patService->setDownUserName($openid,$username);
                }else{
                    //未关注
                    jump(ATTENTION_PAGE);
                    exit();
                }
            }
        }else{
            //没有跳转,需要跳转去认证页面
            $url='';
            $weChat->Oauth_base($url);
            exit();
        }
    }
    if(isset($_SESSION['openid'])){
        $pat=$patService->getPatInfoByOpenid($_SESSION['openid']);
        $relationTree=$patService->getRelationTree($_SESSION['openid']);
        $goldCoin=$patService->getGoldCoin($_SESSION['openid']);
        if(empty($pat)){
            //pat为null,说明没有宠物,跳转到购买宠物的页面
            jump(BUY_PAT_URL);
            exit();
        }else{
            $smarty->assign('pat',$pat);
            $smarty->display('myPat.html');
        }
    }